#!/bin/sh

# .xinitrc in XDG 
alias startx="startx \"$XDG_CONFIG_HOME/X11/xinitrc\""

# Add colour to command outputs
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \

# Alias for simple dotfile management
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

# YouTube video downloading
alias ytmp3="yt-dlp -q --progress -x --audio-format mp3 --audio-quality 0"

# Alias for loading NVM 
alias lnvm='[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
	&& [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"' 

# Minimal Shell Prompt
alias mprompt='export PS1="%n %~ $ "'
