set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo | call mkdir(&undodir, 'p')
set viewdir=$XDG_STATE_HOME/vim/view | call mkdir(&viewdir, 'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif


nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
set nu
syntax on
set autoindent
set splitbelow
set splitright
set tabstop=2
set shiftwidth=2
set softtabstop=2
set wrap
set ignorecase
set showmatch
set hlsearch
set textwidth=0
set formatoptions-=tc
filetype plugin indent on

" Search subfolders for `:find`
set path+=**

" Display all matching files for tab complete
set wildmenu

" :find, :ls, :b

" Display current directory file tree
nnoremap <F2> :!clear && tree -CF --dirsfirst -L 1<CR>
